name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Rebuild native modules
      run: npm rebuild better-sqlite3 --build-from-source

    - name: Build Windows package
      run: npm run build:win

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: dist/

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Rebuild native modules
      run: npm rebuild better-sqlite3 --build-from-source

    - name: Build Linux package
      run: npm run build:linux

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: dist/
