name: Electron Build Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build app (Windows)
      if: matrix.platform == 'win'
      run: npm run build:win
    
    - name: Build app (macOS)
      if: matrix.platform == 'mac'
      run: npm run build:mac
    
    - name: Build app (Linux)
      if: matrix.platform == 'linux'
      run: npm run build:linux
